import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/providers";
import {
  buildOrganizationSchema,
  buildWebSiteSchema,
  buildSoftwareApplicationSchema,
  serializeJsonLd,
} from "@/lib/jsonld";
import { SITE_URL, SITE_NAME, SITE_DESCRIPTION, DEFAULT_OG_IMAGE } from "@/lib/metadata";

// ─── Fonts, self-hosted (no render-blocking, automatic font-display:swap) ────
//
// These were next/font/google, which fetches every face from fonts.gstatic.com
// at BUILD time. That made releases non-deterministic: a v1.36.1 deploy failed
// when Google returned 404 for the Newsreader woff2 files mid-build and
// Turbopack died with 12 "Module not found" errors. Nothing in the commit was
// at fault and a plain re-run succeeded, which is precisely the problem.
//
// Serving the files from the repo removes the network from the build entirely.
// All three are variable fonts, so the whole latin subset is 206 KB across four
// files — fewer requests than the eight static faces Newsreader used to pull.
const inter = localFont({
  src: [{ path: "./fonts/inter-latin-normal.woff2", weight: "100 900", style: "normal" }],
  variable: "--font-inter",
  display: "swap",
});

const jetbrainsMono = localFont({
  src: [{ path: "./fonts/jetbrains-mono-latin-normal.woff2", weight: "100 800", style: "normal" }],
  variable: "--font-mono",
  display: "swap",
});

const newsreader = localFont({
  src: [
    { path: "./fonts/newsreader-latin-normal.woff2", weight: "200 800", style: "normal" },
    { path: "./fonts/newsreader-latin-italic.woff2", weight: "200 800", style: "italic" },
  ],
  variable: "--font-newsreader",
  display: "swap",
});

// ─── Root Metadata ────────────────────────────────────────────────────────────
export const metadata: Metadata = {
  // metadataBase is REQUIRED for absolute OG/Twitter image URLs in Next.js
  metadataBase: new URL(SITE_URL),

  applicationName: SITE_NAME,
  generator: "Next.js",

  title: {
    default: `${SITE_NAME} — AI News Intelligence Platform`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  keywords: [
    "AI news",
    "news intelligence",
    "news aggregator",
    "multi-source news",
    "AI summaries",
    "source comparison",
    "neutral news",
    "fact extraction",
    "news clustering",
    "NewsIQ",
  ],
  authors: [{ name: SITE_NAME, url: SITE_URL }],

  // ── Open Graph ──
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} — AI News Intelligence Platform`,
    description: SITE_DESCRIPTION,
    images: [
      {
        url: DEFAULT_OG_IMAGE,
        width: 1200,
        height: 630,
        alt: "NewsIQ — Understand the Story, Not Just the Headlines",
      },
    ],
  },

  // ── Twitter / X Cards ──
  twitter: {
    card: "summary_large_image",
    site: "@newsiq_app",
    creator: "@newsiq_app",
    title: `${SITE_NAME} — AI News Intelligence Platform`,
    description: SITE_DESCRIPTION,
    images: [DEFAULT_OG_IMAGE],
  },

  // ── Icons — auto-generated by src/app/icon.tsx + src/app/apple-icon.tsx ──
  // Next.js reads those files and builds the correct <link> tags automatically.

  // ── Manifest (PWA / Google Discover) ──
  manifest: "/manifest.json",

  // ── Canonical ──
  alternates: {
    canonical: SITE_URL,
  },

  // ── Robots ──
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  // ── Verification — add tokens once GSC/Bing are connected ──
  // verification: {
  //   google: "YOUR_GOOGLE_SITE_VERIFICATION_TOKEN",
  //   yandex: "YOUR_YANDEX_TOKEN",
  //   other: {
  //     "msvalidate.01": "YOUR_BING_VERIFICATION_TOKEN",
  //   },
  // },

  // ── Referrer policy ──
  referrer: "origin-when-cross-origin",

  // ── Format detection ──
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

// ─── Viewport (themeColor must be here in Next.js 15+) ──────────────────────
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

// ─── Global JSON-LD schemas ───────────────────────────────────────────────────
const orgSchema = buildOrganizationSchema();
const websiteSchema = buildWebSiteSchema();
const appSchema = buildSoftwareApplicationSchema();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${inter.variable} ${jetbrainsMono.variable} ${newsreader.variable}`}
      suppressHydrationWarning
      data-scroll-behavior="smooth"
    >
      <head>
        {/* Global JSON-LD: Organization + WebSite (SearchAction) + SoftwareApplication */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(orgSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(websiteSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: serializeJsonLd(appSchema) }}
        />

        {/* Google Consent Mode v2 Default Settings */}
        <script
          id="google-consent-defaults"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              
              var storedConsent = null;
              try {
                var raw = localStorage.getItem('niq_consent_preferences');
                if (raw) {
                  storedConsent = JSON.parse(raw);
                }
              } catch(e) {}
              
              gtag('consent', 'default', {
                'ad_storage': storedConsent && storedConsent.marketing ? 'granted' : 'denied',
                'ad_user_data': storedConsent && storedConsent.marketing ? 'granted' : 'denied',
                'ad_personalization': storedConsent && storedConsent.marketing ? 'granted' : 'denied',
                'analytics_storage': storedConsent && storedConsent.analytics ? 'granted' : 'denied',
                'functionality_storage': storedConsent && storedConsent.functional ? 'granted' : 'denied',
                'personalization_storage': storedConsent && storedConsent.functional ? 'granted' : 'denied',
                'security_storage': 'granted',
                'wait_for_update': 500
              });
              
              gtag('js', new Date());
            `
          }}
        />

        {/* Google Analytics 4 Script */}
        <script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "G-NEWSIQ"}`}
        />
      </head>
      <body className="min-h-full flex flex-col bg-background text-foreground font-sans">
        {/* Keyboard users otherwise tab through the full navigation on every
            page load — there are nine <nav> blocks across the app. Visually
            hidden until focused (WCAG 2.4.1). */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:rounded-md focus:bg-background focus:px-4 focus:py-2 focus:text-foreground focus:outline-none focus:ring-2 focus:ring-primary"
        >
          Skip to main content
        </a>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
