"""Model package — re-export all models for Alembic discovery."""

from app.models.models import (
    ApiKey,
    Article,
    ArticleEvent,
    Bookmark,
    CanonicalEntity,
    Category,
    DigestSubscription,
    Notification,
    OAuthAccount,
    SearchHistory,
    Session,
    Source,
    Story,
    StoryArticle,
    StoryDifference,
    StoryContradiction,
    StoryEntity,
    StoryMetric,
    StorySourceCoverage,
    StoryTag,
    StoryTimelineEvent,
    User,
    UserCategory,
    UserEvent,
    UserLocation,
    UserPreference,
)
from app.models.consent import ConsentPreference, ConsentAuditLog
from app.models.observability_models import (
    CostRecordModel,
    ErrorLogModel,
    HumanReviewModel,
    LLMTraceModel,
    PipelineRunModel,
    PromptVersionModel,
    QueueMetricsModel,
    RetryHistoryModel,
    StageRunModel,
    TokenUsageModel,
)


__all__ = [
    # Core models
    "ApiKey",
    "Article",
    "ArticleEvent",
    "Bookmark",
    "CanonicalEntity",
    "Category",
    "DigestSubscription",
    "Notification",
    "OAuthAccount",
    "SearchHistory",
    "Session",
    "Source",
    "Story",
    "StoryArticle",
    "StoryDifference",
    "StoryContradiction",
    "StoryEntity",
    "StoryMetric",
    "StorySourceCoverage",
    "StoryTag",
    "StoryTimelineEvent",
    "User",
    "UserCategory",
    "UserEvent",
    "UserLocation",
    "UserPreference",
    "ConsentPreference",
    "ConsentAuditLog",
    # Observability models
    "PipelineRunModel",
    "StageRunModel",
    "LLMTraceModel",
    "TokenUsageModel",
    "CostRecordModel",
    "RetryHistoryModel",
    "ErrorLogModel",
    "PromptVersionModel",
    "QueueMetricsModel",
    "HumanReviewModel",
]
