"""Model package — re-export all models for Alembic discovery."""

from app.models.models import (
    ApiKey,
    Article,
    ArticleEvent,
    Bookmark,
    CanonicalEntity,
    Category,
    DigestSubscription,
    Notification,
    OAuthAccount,
    SearchHistory,
    Session,
    Source,
    Story,
    StoryArticle,
    StoryDifference,
    StoryContradiction,
    StoryEntity,
    StoryMetric,
    StorySourceCoverage,
    StoryTag,
    StoryTimelineEvent,
    User,
    UserCategory,
    UserEvent,
    UserLocation,
    UserPreference,
)
from app.models.consent import ConsentPreference, ConsentAuditLog


__all__ = [
    "ApiKey",
    "Article",
    "ArticleEvent",
    "Bookmark",
    "CanonicalEntity",
    "Category",
    "DigestSubscription",
    "Notification",
    "OAuthAccount",
    "SearchHistory",
    "Session",
    "Source",
    "Story",
    "StoryArticle",
    "StoryDifference",
    "StoryContradiction",
    "StoryEntity",
    "StoryMetric",
    "StorySourceCoverage",
    "StoryTag",
    "StoryTimelineEvent",
    "User",
    "UserCategory",
    "UserEvent",
    "UserLocation",
    "UserPreference",
    "ConsentPreference",
    "ConsentAuditLog",
]
