import { SITE } from "@/lib/site-identity";

export interface PolicySection {
  id: string;
  title: string;
  content: string;
}

export interface PolicyDocument {
  title: string;
  subtitle: string;
  effectiveDate: string;
  version: string;
  lawContext?: string;
  sections: PolicySection[];
}

export interface StorageItem {
  name: string;
  kind: "Cookie" | "Browser storage";
  purpose: string;
  category: "Essential" | "Functional" | "Analytics";
  retention: string;
  thirdParty: string;
  needsConsent: boolean;
}

/**
 * Every cookie and browser-storage key NewsIQ sets, verified against the code.
 * The previous inventory listed names that do not exist (niq_session,
 * niq_cookie_consent) and Meta/LinkedIn trackers the site does not use.
 */
export const storageInventory: StorageItem[] = [
  { name: "access_token", kind: "Cookie", purpose: "Keeps you signed in (short-lived login token; HttpOnly, Secure)", category: "Essential", retention: "15 minutes", thirdParty: "No", needsConsent: false },
  { name: "refresh_token", kind: "Cookie", purpose: "Renews your login without asking for your password (HttpOnly, Secure)", category: "Essential", retention: "30 days", thirdParty: "No", needsConsent: false },
  { name: "niq_consent_preferences", kind: "Browser storage", purpose: "Remembers your cookie choices", category: "Essential", retention: "Until you clear it", thirdParty: "No", needsConsent: false },
  { name: "niq_anonymous_id", kind: "Browser storage", purpose: "Random ID that links your cookie choices to our consent record", category: "Essential", retention: "Until you clear it", thirdParty: "No", needsConsent: false },
  { name: "newsiq-auth", kind: "Browser storage", purpose: "Caches your signed-in profile for the interface", category: "Essential", retention: "Until you sign out", thirdParty: "No", needsConsent: false },
  { name: "resend_cooldown", kind: "Browser storage", purpose: "Prevents repeated verification-email requests", category: "Essential", retention: "60 seconds", thirdParty: "No", needsConsent: false },
  { name: "newsiq-ui", kind: "Browser storage", purpose: "Interface preferences such as sidebar and summary depth", category: "Functional", retention: "Until you clear it", thirdParty: "No", needsConsent: false },
  { name: "theme", kind: "Browser storage", purpose: "Remembers light or dark mode", category: "Functional", retention: "Until you clear it", thirdParty: "No", needsConsent: false },
  { name: "_ga, _ga_*", kind: "Cookie", purpose: "Google Analytics visit measurement", category: "Analytics", retention: "Up to 2 years", thirdParty: "Google", needsConsent: true },
  { name: "ph_*", kind: "Cookie", purpose: "PostHog product analytics", category: "Analytics", retention: "Up to 1 year", thirdParty: "PostHog", needsConsent: true },
];

const EMAIL = SITE.contactEmail;
const EFFECTIVE = SITE.policiesUpdated;
const VERSION = SITE.policiesVersion;

export const normalizedPolicies: Record<string, PolicyDocument> = {
  tos: {
    title: "Terms of Service",
    subtitle: "The rules for using NewsIQ. Please read them before creating an account.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "tos-1",
        title: "Who we are and these terms",
        content: `NewsIQ (${SITE.url}) is operated by ${SITE.operator}, ${SITE.operatorDescription} ("NewsIQ", "we", "us"). These Terms are an agreement between you and us. By using NewsIQ or creating an account, you agree to these Terms and to our Privacy Policy. If you do not agree, please do not use the service.`,
      },
      {
        id: "tos-2",
        title: "Eligibility",
        content: "You may read NewsIQ's public pages without an account. To create an account you must be at least 18 years old and able to enter into a binding agreement.",
      },
      {
        id: "tos-3",
        title: "What NewsIQ does",
        content: "NewsIQ collects news articles from publishers' public RSS feeds and news search, groups articles about the same event into a story, and uses AI to write neutral headlines, summaries, timelines and comparisons of how different outlets covered it. NewsIQ is not a newsroom and does not produce original reporting. Each story links to the original articles, whose copyright stays with their publishers.",
      },
      {
        id: "tos-4",
        title: "Your account",
        content: `You can sign up with an email address and password or with Google. Keep your password confidential; you are responsible for activity on your account. If you think someone else has accessed it, change your password and tell us at ${EMAIL}. You can delete your account at any time in Settings.`,
      },
      {
        id: "tos-5",
        title: "AI-generated content",
        content: "Headlines, summaries, timelines and comparisons on NewsIQ are generated by AI models. They can be wrong, incomplete or out of date, and can misstate what a source said. They are provided for general information only. Check the original articles before relying on anything important, and do not treat NewsIQ as legal, financial, medical or other professional advice.",
      },
      {
        id: "tos-6",
        title: "Publishers' content and copyright notices",
        content: `We show short excerpts, attribution and links rather than republishing full articles. If you are a rights holder and believe material on NewsIQ infringes your rights, send a notice through the copyright form in the Legal Center or to ${EMAIL} (see the Copyright Policy). We review every notice and remove material where appropriate.`,
      },
      {
        id: "tos-7",
        title: "Acceptable use",
        content: "Do not misuse NewsIQ. In particular, do not break the law using it, attempt to access accounts or systems you are not authorised to, interfere with the service, or scrape or bulk-download NewsIQ's pages or API without written permission. The Acceptable Use Policy has the details.",
      },
      {
        id: "tos-8",
        title: "Our intellectual property",
        content: "Apart from publishers' content, the NewsIQ software, design, branding and the headlines and summaries we generate are ours. You may share links to NewsIQ stories and quote short passages with attribution. You may not copy the service or its content at scale.",
      },
      {
        id: "tos-9",
        title: "Paid plans",
        content: "NewsIQ is currently free. A Premium plan is planned but not yet available, and we do not take any payments. Before any paid plan launches, we will publish its price, billing, renewal, cancellation and refund terms, and you will only be charged if you choose to subscribe.",
      },
      {
        id: "tos-10",
        title: "Changes and availability",
        content: "NewsIQ is an early-stage service that is under active development. Features may change or be removed, and the service may sometimes be unavailable. We will give reasonable notice of changes that materially affect you.",
      },
      {
        id: "tos-11",
        title: "Suspension and termination",
        content: "We may suspend or close an account that breaks these Terms or puts the service or other people at risk. You can stop using NewsIQ and delete your account at any time.",
      },
      {
        id: "tos-12",
        title: "Disclaimer",
        content: "NewsIQ is provided \"as is\" and \"as available\". To the extent the law allows, we make no warranties about the accuracy, completeness or availability of the service or its AI-generated content.",
      },
      {
        id: "tos-13",
        title: "Limitation of liability",
        content: "To the extent the law allows, we are not liable for indirect or consequential losses, or for decisions made on the basis of AI-generated content or publishers' articles. Nothing in these Terms limits liability that cannot be limited by law, or your rights as a consumer.",
      },
      {
        id: "tos-14",
        title: "Governing law",
        content: `These Terms are governed by the laws of ${SITE.country}. We will first try to resolve any dispute informally; please contact us at ${EMAIL}. Otherwise, disputes are subject to the courts of competent jurisdiction in ${SITE.country}.`,
      },
      {
        id: "tos-15",
        title: "Changes to these Terms and contact",
        content: `We may update these Terms. The date at the top shows the latest version, and we will tell registered users about material changes by email or on the site. Questions: ${EMAIL}.`,
      },
    ],
  },

  privacy: {
    title: "Privacy Policy",
    subtitle: "What personal data NewsIQ collects, why, who processes it, and the choices you have.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    lawContext: "India DPDP Act 2023 · GDPR",
    sections: [
      {
        id: "priv-1",
        title: "Who we are",
        content: `NewsIQ (${SITE.url}) is operated by ${SITE.operator}, ${SITE.operatorDescription}. For the personal data described here, ${SITE.operator} is the Data Fiduciary under India's Digital Personal Data Protection Act, 2023, and the controller under the GDPR for users in the EU and UK. Contact: ${EMAIL}.`,
      },
      {
        id: "priv-2",
        title: "Data we collect",
        content: "(a) Account data: your email address and name, and a password hash (argon2id, never the password itself) if you sign up with email. If you use Google sign-in, we receive your name, email address, profile picture and Google account ID. (b) Preferences: topics, theme, digest and notification settings. (c) Activity while signed in: bookmarks, searches, and the stories you open, used to personalise your feed. (d) Consent records: your cookie choices, with a random ID and timestamp. (e) Technical data: IP address and browser details in server logs, rate limiting and error reports. (f) Analytics, only if you allow it (see Cookies). (g) Anything you send us, such as a support or privacy request. We do not collect payment data: NewsIQ takes no payments.",
      },
      {
        id: "priv-3",
        title: "How we use it",
        content: "To run your account and the service; to personalise your feed and digests; to send the emails you need or ask for (email verification, password resets, digests you subscribe to); to keep NewsIQ secure and prevent abuse; to understand how the site is used, if you allow analytics; and to meet legal obligations. We do not sell personal data and we do not show advertising.",
      },
      {
        id: "priv-4",
        title: "Legal bases",
        content: "Under the DPDP Act we process personal data with your consent, or for legitimate uses the Act permits. Under the GDPR the bases are: performance of our contract with you (your account and its features), consent (analytics cookies, optional emails), and legitimate interests (security, abuse prevention, fixing errors).",
      },
      {
        id: "priv-5",
        title: "AI processing",
        content: "Our AI models process news articles (publicly published text), not your account data. To generate summaries we use Google Gemini, and models reached through OpenRouter (DeepSeek, Inception Mercury and Qwen embeddings); AWS Bedrock is configured as a fallback, and Langfuse monitors AI quality. We do not send your name, email or reading history to these providers. Personalisation runs in our own systems.",
      },
      {
        id: "priv-6",
        title: "Service providers",
        content: "We use these providers to run NewsIQ, each only for its stated purpose: Google Cloud (hosting, in Singapore); Google (Google sign-in, sending email through Gmail, Google Analytics if you allow it, and Gemini AI); PostHog (product analytics, if you allow it); Sentry (error monitoring); OpenRouter and the model hosts it routes to, AWS Bedrock, and Langfuse (AI processing and monitoring of news articles).",
      },
      {
        id: "priv-7",
        title: "Where data is stored",
        content: "Our servers and database are on Google Cloud in Singapore. Some providers above process data in other countries, including the United States, the EU and Japan. Where the law requires safeguards for such transfers, we rely on the providers' standard contractual terms.",
      },
      {
        id: "priv-8",
        title: "How long we keep it",
        content: "Account data, preferences, bookmarks, search history and activity: until you delete your account. Consent records: kept, but disconnected from you when you delete your account. AI monitoring data held in our systems: deleted after 30 days. Server logs: rotated automatically and kept only briefly. Error reports: kept by Sentry under its retention settings. Messages you send us: as long as needed to handle your request.",
      },
      {
        id: "priv-9",
        title: "Deleting your account and exporting your data",
        content: `In Settings you can download a copy of your data (profile, preferences, bookmarks, notifications and reading history) and delete your account. Deletion takes effect immediately: we delete your preferences, bookmarks, search history, activity, digest subscriptions and consent settings, remove your Google sign-in link, and replace your name and email with anonymous values. You can also ask us at ${EMAIL}.`,
      },
      {
        id: "priv-10",
        title: "Your rights",
        content: `Depending on where you live, you can ask to access, correct or erase your personal data, to receive a copy of it, to object to or restrict processing, to withdraw consent at any time (for cookies, from the cookie settings), and, under the DPDP Act, to nominate someone to exercise your rights. Use Settings, the Privacy Rights form in the Legal Center, or email ${EMAIL}. We reply within 30 days. You can also complain to the Data Protection Board of India or your local data protection authority.`,
      },
      {
        id: "priv-11",
        title: "Grievance Officer",
        content: `Grievance Officer: ${SITE.grievanceOfficer}, ${EMAIL}. We acknowledge grievances within 24 hours and aim to resolve them within 15 days.`,
      },
      {
        id: "priv-12",
        title: "Children",
        content: `NewsIQ accounts are for people aged 18 and over. We do not knowingly collect personal data from children. If you believe a child has created an account, contact ${EMAIL} and we will delete it.`,
      },
      {
        id: "priv-13",
        title: "Security",
        content: "We use HTTPS for all traffic, hash passwords with argon2id, keep login tokens in HttpOnly cookies, keep the database off the public internet, and use Google Cloud's encryption at rest. No system is perfectly secure. If a breach affects your personal data, we will notify you and the authorities as Indian law requires. See the Security page for details.",
      },
      {
        id: "priv-14",
        title: "Changes to this policy",
        content: "We will post changes here and update the date at the top. If a change materially affects how we use your data, we will tell registered users by email or on the site.",
      },
    ],
  },

  cookies: {
    title: "Cookie Policy",
    subtitle: "The cookies and browser storage NewsIQ uses, and how to control them.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "cook-1",
        title: "What we use",
        content: "Cookies are small files a website stores in your browser; browser storage (local storage) is similar but is not sent to the server automatically. NewsIQ uses both. The full list is in the table below.",
      },
      {
        id: "cook-2",
        title: "Essential and functional",
        content: "Essential items keep you signed in and remember your cookie choices; the site does not work properly without them, so they do not need consent. Functional items remember interface preferences such as dark mode. None of these are shared with third parties.",
      },
      {
        id: "cook-3",
        title: "Analytics: only with your permission",
        content: "If you allow analytics, we use Google Analytics and PostHog to understand which pages and features people use. Their cookies are set only after you opt in. Until then, Google Analytics runs in its consent mode: it can receive basic, cookieless signals (such as a page having loaded) but stores no identifier in your browser.",
      },
      {
        id: "cook-4",
        title: "No advertising trackers",
        content: "NewsIQ shows no ads and uses no advertising, retargeting or social-media tracking pixels. Google's advertising signals are always set to \"denied\".",
      },
      {
        id: "cook-5",
        title: "Your choices",
        content: "Use the cookie banner or Cookie Settings to accept or reject analytics, and change your mind at any time; withdrawing consent reloads the page and stops analytics. You can also clear or block cookies in your browser, but blocking essential cookies will sign you out.",
      },
    ],
  },

  security: {
    title: "Security",
    subtitle: "How we protect NewsIQ and your data, what we don't do yet, and how to report a vulnerability.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "sec-1",
        title: "Encryption",
        content: "All traffic uses HTTPS with certificates from Let's Encrypt. Plain HTTP is redirected, and browsers are told to use HTTPS only (HSTS). Data at rest sits on Google Cloud disks, which Google encrypts by default.",
      },
      {
        id: "sec-2",
        title: "Accounts and sessions",
        content: "Passwords are hashed with argon2id and are never stored or logged in plain text. Login tokens are kept in HttpOnly, Secure, SameSite cookies that page scripts cannot read. Access tokens expire after 15 minutes. Refresh tokens last 30 days and are stored only as hashes. Sign-in and other endpoints are rate-limited.",
      },
      {
        id: "sec-3",
        title: "Infrastructure",
        content: "NewsIQ runs on Google Cloud in Singapore. The database, cache and search services are reachable only inside the server's private network, not from the internet. The only public entry points are the website, the API and the admin dashboard, all over HTTPS. Server access uses SSH keys only, and administrative features require an administrator account.",
      },
      {
        id: "sec-4",
        title: "Code and dependencies",
        content: "Every change runs automated tests and security scans: static analysis (CodeQL), container vulnerability scanning (Trivy), a Python dependency audit, and secret scanning. Errors are monitored in production.",
      },
      {
        id: "sec-5",
        title: "What we don't have yet",
        content: "NewsIQ is operated by one person. There is not yet two-factor authentication for user accounts, no formal certification such as ISO 27001 or SOC 2, and no bug bounty. We would rather say so than overstate it.",
      },
      {
        id: "sec-6",
        title: "Reporting a vulnerability",
        content: `Email ${EMAIL} with "Security" in the subject, and describe the issue and how to reproduce it. Please act in good faith: do not access other people's data, disrupt the service or publish details before we have fixed it. We acknowledge reports within 72 hours and will keep you updated. Our security.txt is at ${SITE.url}/.well-known/security.txt.`,
      },
      {
        id: "sec-7",
        title: "Incidents",
        content: "If a security incident affects personal data, we will contain it, notify affected users, and report it to CERT-In and the Data Protection Board of India as the law requires.",
      },
    ],
  },

  ai: {
    title: "Responsible AI",
    subtitle: "How NewsIQ uses AI, and its limits.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "ai-1",
        title: "What the AI does",
        content: "AI models group articles about the same event, extract who, what and where, and write neutral headlines, summaries at three lengths, timelines and comparisons of how different outlets covered a story.",
      },
      {
        id: "ai-2",
        title: "Which models",
        content: "Google Gemini is the primary model. When it is unavailable, requests go to other models through OpenRouter (DeepSeek, Inception Mercury) and, as a last fallback, AWS Bedrock. Embeddings for grouping similar articles come from Qwen via OpenRouter.",
      },
      {
        id: "ai-3",
        title: "Checks on the output",
        content: "Generated summaries are checked against the source articles for invented or omitted facts, and stories are reviewed by an AI reviewer before they are published. These checks reduce errors but cannot remove them.",
      },
      {
        id: "ai-4",
        title: "Limits",
        content: "AI output can be wrong, can reflect bias in its sources, and can miss context. Everything AI-generated is labelled as such and links to the original reporting so you can check it.",
      },
    ],
  },

  aup: {
    title: "Acceptable Use Policy",
    subtitle: "What you may not do on NewsIQ.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "aup-1",
        title: "Lawful use",
        content: "Use NewsIQ only for lawful purposes and in line with these rules and the Terms of Service.",
      },
      {
        id: "aup-2",
        title: "Not allowed",
        content: "Fraud or impersonation; harassment or threats; attempting to access accounts, data or systems you are not authorised to; probing, scanning or load-testing our systems without permission (report vulnerabilities through the Security page instead); introducing malware; or sharing your account.",
      },
      {
        id: "aup-3",
        title: "Scraping and bulk use",
        content: "Do not scrape, crawl or bulk-download NewsIQ's pages or API, or use them to train AI models or build datasets, without our written permission. Search engines' normal indexing is welcome.",
      },
      {
        id: "aup-4",
        title: "Enforcement and reporting",
        content: `We may limit, suspend or close accounts that break these rules. Report abuse through the Legal Center's abuse form or to ${EMAIL}.`,
      },
    ],
  },

  dmca: {
    title: "Copyright Policy",
    subtitle: "How rights holders can report content and how we respond.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "dmca-1",
        title: "Our approach",
        content: "NewsIQ credits the publisher of every article it references and links to the original. We publish AI-written summaries and short excerpts, not full articles. Copyright in the original articles stays with their publishers.",
      },
      {
        id: "dmca-2",
        title: "Sending a notice",
        content: `Use the copyright form in the Legal Center or email ${EMAIL}. Include: who you are and your contact details; the work you own; the NewsIQ URL of the material; why you believe it infringes; and a statement that the information is accurate and that you are the rights holder or authorised to act for them.`,
      },
      {
        id: "dmca-3",
        title: "What happens next",
        content: "We acknowledge notices within 24 hours and aim to decide within 15 days. Where a notice is valid, we remove or change the material and let you know.",
      },
      {
        id: "dmca-4",
        title: "Publishers",
        content: `Publishers who want their feed excluded, or a different attribution format, can write to ${EMAIL} and we will accommodate reasonable requests.`,
      },
    ],
  },

  attribution: {
    title: "Attribution & Sources",
    subtitle: "How NewsIQ credits the journalism it builds on.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "attr-1",
        title: "How we credit sources",
        content: "Every story names the publishers it draws on, links to each original article, and shows when it was published.",
      },
      {
        id: "attr-2",
        title: "Summaries complement the original",
        content: "Our summaries help readers see how a story developed across outlets. They are meant to send readers to the original reporting, not to replace it.",
      },
      {
        id: "attr-3",
        title: "Where articles come from",
        content: "NewsIQ reads the public RSS feeds of about 30 publishers, and finds further coverage of the same events through news search.",
      },
      {
        id: "attr-4",
        title: "Publisher requests",
        content: `Publishers with questions or requests about attribution or inclusion can contact ${EMAIL}.`,
      },
    ],
  },

  disclaimer: {
    title: "Disclaimer",
    subtitle: "The limits of what NewsIQ provides.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "disc-1",
        title: "General information only",
        content: "NewsIQ helps you follow news stories. Everything on it is general information, provided as is.",
      },
      {
        id: "disc-2",
        title: "Not professional advice",
        content: "Nothing on NewsIQ is legal, financial, investment, medical or other professional advice.",
      },
      {
        id: "disc-3",
        title: "AI accuracy",
        content: "Summaries and comparisons are generated by AI and can be wrong or incomplete. Check the linked original articles.",
      },
      {
        id: "disc-4",
        title: "Third-party sites",
        content: "We link to publishers' websites but do not control them and are not responsible for their content.",
      },
    ],
  },

  retention: {
    title: "Data Retention",
    subtitle: "How long NewsIQ keeps each kind of data.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "ret-1",
        title: "Retention periods",
        content: "Account data, preferences, bookmarks, search history and activity: until you delete your account. Consent records: kept, but disconnected from you when you delete your account. AI monitoring data held in our systems: 30 days. Server logs: rotated automatically and kept only briefly. Messages you send us: as long as needed to handle the request.",
      },
      {
        id: "ret-2",
        title: "Deleting your account",
        content: "Account deletion in Settings takes effect immediately. It deletes your personal data from our database, and replaces your name and email with anonymous values so they cannot identify you.",
      },
      {
        id: "ret-3",
        title: "Getting a copy",
        content: "In Settings you can download your data as a file at any time.",
      },
    ],
  },

  subscription: {
    title: "Premium (Coming Soon)",
    subtitle: "NewsIQ is free today. This page will hold the paid-plan terms once they exist.",
    effectiveDate: EFFECTIVE,
    version: VERSION,
    sections: [
      {
        id: "sub-1",
        title: "No payments yet",
        content: "NewsIQ does not currently sell subscriptions or take payments. The Premium plan shown on the site is planned but not yet available.",
      },
      {
        id: "sub-2",
        title: "Before any paid plan launches",
        content: "We will publish its price, billing cycle, renewal, cancellation and refund terms here before anyone can subscribe, and you will only be charged if you choose a paid plan.",
      },
    ],
  },
};
