"""Continuously merge stories that describe the same event.

The gap this closes
-------------------
Clustering evaluates an article exactly once — at extraction time, against the
stories that existed at that instant. Nothing ever revisits an already-clustered
article, and no process ever compares two *stories* to each other.

That makes fragmentation permanent by construction, independent of how good the
scoring is. Two articles about the same event that arrive in different batches
each create a story, and those two stories are never compared again. Measured on
production: 41 duplicate groups across 144 stories (28%), including five separate
"OpenAI launches ChatGPT desktop app for Linux" stories.

Every clustering bug found so far — the Stage A anchor deadlock, centroids
stranded in a previous embedding model's vector space — also left permanent
fragmentation behind, because fixing the scoring forward cannot repair stories
that were already split.

Running this on a schedule makes the system self-healing: a merge missed for any
reason (batch boundary, transient provider failure, a scoring regression later
corrected) is caught on a subsequent pass rather than persisting forever.

Design constraints
------------------
* Uses the SAME Stage A/B validators as the live incremental path. No bespoke
  similarity logic, so a merge here means exactly what a merge means in
  production, and a scoring change applies to both automatically.
* Bounded per run (window + max merges) so a scoring regression cannot collapse
  the corpus in one pass — the blast radius of a bad run is capped and visible.
* User-owned rows (bookmarks, user_events) are repointed at the surviving story,
  never deleted. Derived rows are dropped and regenerated by synthesis.
"""

import logging
import uuid
from datetime import UTC, datetime, timedelta
from typing import Any

import numpy as np
from sqlalchemy import delete, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import async_session_factory
from app.models.models import Article, ArticleEntity, Story, StoryArticle, StoryEntity
from app.services.event_validation_service import StoryAnchor, event_validation_service
from app.services.vector_service import vector_service

logger = logging.getLogger(__name__)

# Cheap centroid pre-filter before running the real validators. Deliberately far
# below Stage B's threshold so it can only skip pairs the validators would have
# rejected anyway — it must never be the thing that decides a merge.
CENTROID_PREFILTER = 0.60

# Derived per-story rows: safe to drop on merge because synthesis rebuilds them
# for the survivor. bookmarks/user_events are absent by design — they represent a
# user's relationship to the story and are repointed instead, since deleting them
# would destroy someone's saved story to tidy up a clustering mistake.
DERIVED_CHILD_TABLES = (
    "story_timeline_events",
    "story_source_coverage",
    "story_differences",
    "story_entities",
    "story_tags",
    "story_contradictions",
    "story_metrics",
    "story_versions",
    "story_evolutions",
    "synthesis_artifacts",
    "story_reviews",
    "story_articles",
)

USER_OWNED_TABLES = (("bookmarks", "user_id"), ("user_events", "user_id"))


def _cosine(a: list[float] | None, b: list[float] | None) -> float:
    if not a or not b:
        return 0.0
    va, vb = np.asarray(a, dtype=float), np.asarray(b, dtype=float)
    na, nb = float(np.linalg.norm(va)), float(np.linalg.norm(vb))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return float(va @ vb / (na * nb))


async def _anchor_for(story: Story, session: AsyncSession) -> StoryAnchor:
    rows = (
        await session.execute(
            select(StoryEntity.entity_value, StoryEntity.entity_type).where(
                StoryEntity.story_id == story.id
            )
        )
    ).all()
    now = datetime.now(UTC).replace(tzinfo=None)
    return StoryAnchor(
        story_id=str(story.id),
        headline=story.headline or "",
        first_seen_at=story.first_seen_at or now,
        last_updated_at=story.updated_at or now,
        primary_entities={v.lower() for v, _ in rows if v},
        top_locations={v.lower() for v, t in rows if v and t in ("GPE", "LOC")},
        category=None,
        event_type=None,
        centroid_vector=story.story_embedding,
        entity_graph_ids=set(),
    )


class StoryReconciliationService:
    """Finds and merges duplicate stories using the production validators."""

    async def find_duplicates(self, hours: int, session: AsyncSession) -> list[dict[str, Any]]:
        """Return merge candidates, newest-first, without writing anything."""
        cutoff = datetime.now(UTC).replace(tzinfo=None) - timedelta(hours=hours)

        stories = list(
            (
                await session.execute(
                    select(Story)
                    .where(Story.created_at >= cutoff, Story.story_embedding.isnot(None))
                    .order_by(Story.created_at.asc())
                )
            )
            .scalars()
            .all()
        )
        if len(stories) < 2:
            return []

        sizes: dict[uuid.UUID, list[uuid.UUID]] = {}
        for story in stories:
            sizes[story.id] = list(
                (
                    await session.execute(
                        select(StoryArticle.article_id).where(StoryArticle.story_id == story.id)
                    )
                )
                .scalars()
                .all()
            )

        absorbed: set[uuid.UUID] = set()
        found: list[dict[str, Any]] = []

        for i, story_a in enumerate(stories):
            if story_a.id in absorbed:
                continue
            for story_b in stories[i + 1 :]:
                if story_b.id in absorbed:
                    continue
                if _cosine(story_a.story_embedding, story_b.story_embedding) < CENTROID_PREFILTER:
                    continue

                # Keep the larger story; ties resolve to the older one, so the
                # canonical id and its accumulated history survive.
                a_n, b_n = len(sizes.get(story_a.id, [])), len(sizes.get(story_b.id, []))
                keep, drop = (story_a, story_b) if a_n >= b_n else (story_b, story_a)

                drop_articles = sizes.get(drop.id, [])
                if not drop_articles:
                    continue
                article = (
                    await session.execute(select(Article).where(Article.id == drop_articles[0]))
                ).scalar_one_or_none()
                if article is None:
                    continue

                art_ents = set(
                    (
                        await session.execute(
                            select(ArticleEntity.entity_value).where(
                                ArticleEntity.article_id == article.id
                            )
                        )
                    )
                    .scalars()
                    .all()
                )
                anchor = await _anchor_for(keep, session)

                decision_a = event_validation_service.validate_stage_a(
                    article, anchor, article_entities=art_ents
                )
                if decision_a.outcome.value == "FAIL":
                    continue

                vectors = await vector_service.retrieve_vectors([str(article.id)])
                if not vectors:
                    continue
                decision_b = event_validation_service.validate_stage_b(
                    article, anchor, list(vectors.values())[0], set()
                )
                if decision_b.outcome.value != "PASS":
                    continue

                absorbed.add(drop.id)
                found.append(
                    {
                        "keep_id": keep.id,
                        "drop_id": drop.id,
                        "keep_headline": keep.headline,
                        "drop_headline": drop.headline,
                        "stage_a": round(decision_a.score, 1),
                        "stage_b": round(decision_b.score, 3),
                    }
                )
        return found

    async def merge(self, keep_id: uuid.UUID, drop_id: uuid.UUID) -> bool:
        """Fold `drop` into `keep`. Returns True on success."""
        async with async_session_factory() as session:
            try:
                keep_articles = set(
                    (
                        await session.execute(
                            select(StoryArticle.article_id).where(StoryArticle.story_id == keep_id)
                        )
                    )
                    .scalars()
                    .all()
                )
                drop_articles = (
                    (
                        await session.execute(
                            select(StoryArticle.article_id).where(StoryArticle.story_id == drop_id)
                        )
                    )
                    .scalars()
                    .all()
                )
                for article_id in drop_articles:
                    if article_id not in keep_articles:
                        session.add(StoryArticle(story_id=keep_id, article_id=article_id))

                # Repoint user-owned rows, dropping only those that would violate
                # the (user, story) uniqueness because the user already holds the
                # survivor.
                for table, user_col in USER_OWNED_TABLES:
                    await session.execute(
                        text(
                            f"DELETE FROM {table} WHERE story_id = :drop AND {user_col} IN "  # noqa: S608
                            f"(SELECT {user_col} FROM {table} WHERE story_id = :keep)"
                        ),
                        {"drop": drop_id, "keep": keep_id},
                    )
                    await session.execute(
                        text(f"UPDATE {table} SET story_id = :keep WHERE story_id = :drop"),  # noqa: S608
                        {"drop": drop_id, "keep": keep_id},
                    )

                # Circular FK must be broken before story_versions is deleted.
                await session.execute(
                    text("UPDATE stories SET current_version_id = NULL WHERE id = :d"),
                    {"d": drop_id},
                )
                await session.execute(
                    text("UPDATE story_candidates SET story_id = NULL WHERE story_id = :d"),
                    {"d": drop_id},
                )
                for table in DERIVED_CHILD_TABLES:
                    await session.execute(
                        text(f"DELETE FROM {table} WHERE story_id = :d"),  # noqa: S608
                        {"d": drop_id},
                    )
                await session.execute(delete(Story).where(Story.id == drop_id))
                await session.commit()
            except Exception as exc:
                await session.rollback()
                logger.error("Merge %s <- %s failed: %s", keep_id, drop_id, exc)
                return False

        # The survivor's centroid and anchor must reflect its new membership, or
        # the next pass compares against a stale identity.
        async with async_session_factory() as session:
            try:
                from app.services.clustering_service import clustering_service

                story = (
                    await session.execute(select(Story).where(Story.id == keep_id))
                ).scalar_one_or_none()
                if story is None:
                    return True
                members = list(
                    (
                        await session.execute(
                            select(StoryArticle.article_id).where(StoryArticle.story_id == keep_id)
                        )
                    )
                    .scalars()
                    .all()
                )
                await clustering_service.refresh_story_centroid(story, session, article_ids=members)
                await clustering_service.seed_story_anchor(story, members, session)
                await session.commit()
            except Exception as exc:
                await session.rollback()
                logger.error("Post-merge refresh failed for %s: %s", keep_id, exc)
        return True

    async def reconcile(self, hours: int = 48, max_merges: int = 25) -> dict[str, int]:
        """Find and apply duplicate merges, bounded.

        max_merges caps the blast radius: if a scoring change ever makes the
        validators too permissive, one scheduled run can affect at most this many
        stories, and the cap being hit is logged as a signal rather than silently
        absorbed.
        """
        async with async_session_factory() as session:
            candidates = await self.find_duplicates(hours, session)

        if not candidates:
            return {"found": 0, "merged": 0, "skipped": 0}

        capped = candidates[:max_merges]
        if len(candidates) > max_merges:
            logger.warning(
                "Story reconciliation found %d duplicate pairs but is capped at %d this run. "
                "The remainder will be handled on the next pass.",
                len(candidates),
                max_merges,
            )

        merged = 0
        for cand in capped:
            logger.info(
                "Merging story %s <- %s (stageA=%s stageB=%s): %r absorbs %r",
                str(cand["keep_id"])[:8],
                str(cand["drop_id"])[:8],
                cand["stage_a"],
                cand["stage_b"],
                (cand["keep_headline"] or "")[:60],
                (cand["drop_headline"] or "")[:60],
            )
            if await self.merge(cand["keep_id"], cand["drop_id"]):
                merged += 1

        return {"found": len(candidates), "merged": merged, "skipped": len(candidates) - merged}


story_reconciliation_service = StoryReconciliationService()
