"""create_discovery_and_crawl_tasks

Revision ID: 1af5d702f838
Revises: 5bdb4b86da16
Create Date: 2026-07-14 01:23:00.071326
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1af5d702f838'
down_revision: Union[str, None] = '5bdb4b86da16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('priority_reason', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('task_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('search_started_at', sa.DateTime(), nullable=True),
    sa.Column('search_completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_discovery_tasks_created', 'discovery_tasks', ['created_at'], unique=False)
    op.create_index('idx_discovery_tasks_priority', 'discovery_tasks', ['priority', 'created_at'], unique=False)
    op.create_index('idx_discovery_tasks_status', 'discovery_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_discovery_tasks_article_id'), 'discovery_tasks', ['article_id'], unique=False)
    op.create_index(op.f('ix_discovery_tasks_created_at'), 'discovery_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_discovery_tasks_next_retry_at'), 'discovery_tasks', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_discovery_tasks_priority'), 'discovery_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_discovery_tasks_status'), 'discovery_tasks', ['status'], unique=False)
    op.create_table('crawl_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discovery_task_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('task_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('crawl_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discovery_task_id'], ['discovery_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawl_tasks_status_outcome', 'crawl_tasks', ['status', 'outcome'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_article_id'), 'crawl_tasks', ['article_id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_created_at'), 'crawl_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_discovery_task_id'), 'crawl_tasks', ['discovery_task_id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_next_retry_at'), 'crawl_tasks', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_status'), 'crawl_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_url_hash'), 'crawl_tasks', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_tasks_url_hash'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_status'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_next_retry_at'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_discovery_task_id'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_created_at'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_article_id'), table_name='crawl_tasks')
    op.drop_index('idx_crawl_tasks_status_outcome', table_name='crawl_tasks')
    op.drop_table('crawl_tasks')
    op.drop_index(op.f('ix_discovery_tasks_status'), table_name='discovery_tasks')
    op.drop_index(op.f('ix_discovery_tasks_priority'), table_name='discovery_tasks')
    op.drop_index(op.f('ix_discovery_tasks_next_retry_at'), table_name='discovery_tasks')
    op.drop_index(op.f('ix_discovery_tasks_created_at'), table_name='discovery_tasks')
    op.drop_index(op.f('ix_discovery_tasks_article_id'), table_name='discovery_tasks')
    op.drop_index('idx_discovery_tasks_status', table_name='discovery_tasks')
    op.drop_index('idx_discovery_tasks_priority', table_name='discovery_tasks')
    op.drop_index('idx_discovery_tasks_created', table_name='discovery_tasks')
    op.drop_table('discovery_tasks')
    # ### end Alembic commands ###
