"""refactor_auth_sessions

Revision ID: 269a315225ab
Revises: 0001_initial_schema
Create Date: 2026-06-13 22:53:46.911366
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "269a315225ab"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("token_hash", sa.String(length=64), nullable=False))
    op.add_column("sessions", sa.Column("device_name", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("last_used_at", sa.DateTime(), nullable=False))
    op.alter_column("sessions", "expires_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("sessions", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.drop_constraint(op.f("sessions_token_key"), "sessions", type_="unique")
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.drop_constraint(op.f("sessions_user_id_fkey"), "sessions", type_="foreignkey")
    op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_column("sessions", "token")
    op.add_column("users", sa.Column("failed_login_attempts", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("locked_until", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    op.add_column(
        "users", sa.Column("email_verification_token", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("email_verification_expiry", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("password_reset_token", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("password_reset_expiry", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_users_email_verification_token"),
        "users",
        ["email_verification_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_password_reset_token"), "users", ["password_reset_token"], unique=False
    )
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_password_reset_token"), table_name="users")
    op.drop_index(op.f("ix_users_email_verification_token"), table_name="users")
    op.drop_column("users", "password_reset_expiry")
    op.drop_column("users", "password_reset_token")
    op.drop_column("users", "email_verification_expiry")
    op.drop_column("users", "email_verification_token")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    op.add_column("sessions", sa.Column("token", sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(op.f("sessions_user_id_fkey"), "sessions", "users", ["user_id"], ["id"])
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.create_unique_constraint(
        op.f("sessions_token_key"), "sessions", ["token"], postgresql_nulls_not_distinct=False
    )
    op.alter_column("sessions", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("sessions", "expires_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.drop_column("sessions", "last_used_at")
    op.drop_column("sessions", "device_name")
    op.drop_column("sessions", "token_hash")
    # ### end Alembic commands ###
