"""add_digest_settings_to_user_preferences

Revision ID: 2d9b11a0701c
Revises: 269a315225ab
Create Date: 2026-06-16 20:22:34.736246
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d9b11a0701c"
down_revision: str | None = "269a315225ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_preferences",
        sa.Column("digest_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preferences", "digest_settings")
    # ### end Alembic commands ###
