"""add_consent_tables

Revision ID: 3efcc4470451
Revises: a8f3c2e1d9b7
Create Date: 2026-06-19 11:17:04.345122
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3efcc4470451'
down_revision: Union[str, None] = 'a8f3c2e1d9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_audit_logs_anonymous_id'), 'consent_audit_logs', ['anonymous_id'], unique=False)
    op.create_index(op.f('ix_consent_audit_logs_user_id'), 'consent_audit_logs', ['user_id'], unique=False)
    op.create_table('consent_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=255), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('functional', sa.Boolean(), nullable=False),
    sa.Column('analytics', sa.Boolean(), nullable=False),
    sa.Column('marketing', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_preferences_anonymous_id'), 'consent_preferences', ['anonymous_id'], unique=True)
    op.create_index(op.f('ix_consent_preferences_user_id'), 'consent_preferences', ['user_id'], unique=True)
    op.alter_column('stories', 'key_facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ordered list of bullet-point facts extracted by Gemini AI',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'key_facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered list of bullet-point facts extracted by Gemini AI',
               existing_nullable=True)
    op.drop_index(op.f('ix_consent_preferences_user_id'), table_name='consent_preferences')
    op.drop_index(op.f('ix_consent_preferences_anonymous_id'), table_name='consent_preferences')
    op.drop_table('consent_preferences')
    op.drop_index(op.f('ix_consent_audit_logs_user_id'), table_name='consent_audit_logs')
    op.drop_index(op.f('ix_consent_audit_logs_anonymous_id'), table_name='consent_audit_logs')
    op.drop_table('consent_audit_logs')
    # ### end Alembic commands ###
