"""add_ui_settings_to_user_preferences

Revision ID: 50cf1906f934
Revises: 2d9b11a0701c
Create Date: 2026-06-17 09:06:20.490006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50cf1906f934'
down_revision: Union[str, None] = '2d9b11a0701c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('ui_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'ui_settings')
    # ### end Alembic commands ###
