"""epic7_synthesis_schema

Revision ID: 5bdb4b86da16
Revises: bedb1fd68ec8
Create Date: 2026-07-10 20:15:00.829788
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bdb4b86da16"
down_revision: str | None = "bedb1fd68ec8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Reference variables to satisfy CodeQL static analysis checks
_alembic_refs = (revision, down_revision, branch_labels, depends_on)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_traces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=True),
        sa.Column("article_id", sa.UUID(), nullable=True),
        sa.Column("canonical_event_id", sa.String(length=128), nullable=True),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("decision", sa.String(length=50), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pipeline_traces_story_stage", "pipeline_traces", ["story_id", "stage"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_traces_article_id"), "pipeline_traces", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_traces_canonical_event_id"),
        "pipeline_traces",
        ["canonical_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_traces_created_at"), "pipeline_traces", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_pipeline_traces_stage"), "pipeline_traces", ["stage"], unique=False)
    op.create_index(
        op.f("ix_pipeline_traces_story_id"), "pipeline_traces", ["story_id"], unique=False
    )
    op.create_table(
        "synthesis_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_id", "artifact_type", "content_hash"),
    )
    op.create_index(
        "idx_synthesis_artifacts_hash",
        "synthesis_artifacts",
        ["story_id", "artifact_type", "content_hash"],
        unique=False,
    )
    op.create_table(
        "story_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=20), nullable=False),
        sa.Column("summary_artifact_id", sa.UUID(), nullable=True),
        sa.Column("timeline_artifact_id", sa.UUID(), nullable=True),
        sa.Column("kg_artifact_id", sa.UUID(), nullable=True),
        sa.Column("source_comparison_artifact_id", sa.UUID(), nullable=True),
        sa.Column("contradiction_artifact_id", sa.UUID(), nullable=True),
        sa.Column("llm_cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("trigger", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contradiction_artifact_id"],
            ["synthesis_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kg_artifact_id"],
            ["synthesis_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_comparison_artifact_id"],
            ["synthesis_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["summary_artifact_id"],
            ["synthesis_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["timeline_artifact_id"],
            ["synthesis_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_id", "version_number"),
    )
    op.create_index(
        "idx_story_versions_story", "story_versions", ["story_id", "version_number"], unique=False
    )
    op.create_table(
        "story_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("story_version_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("summary_quality", sa.Integer(), nullable=False),
        sa.Column("hallucination_count", sa.Integer(), nullable=False),
        sa.Column("missing_facts_count", sa.Integer(), nullable=False),
        sa.Column("contradiction_accuracy", sa.Integer(), nullable=False),
        sa.Column("source_coverage_score", sa.Integer(), nullable=False),
        sa.Column("source_diversity_score", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_version_id"],
            ["story_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("stories", sa.Column("current_version_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_stories_current_version_id",
        "stories",
        "story_versions",
        ["current_version_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_stories_current_version_id", "stories", type_="foreignkey")
    op.drop_column("stories", "current_version_id")
    op.drop_table("story_reviews")
    op.drop_index("idx_story_versions_story", table_name="story_versions")
    op.drop_table("story_versions")
    op.drop_index("idx_synthesis_artifacts_hash", table_name="synthesis_artifacts")
    op.drop_table("synthesis_artifacts")
    op.drop_index(op.f("ix_pipeline_traces_story_id"), table_name="pipeline_traces")
    op.drop_index(op.f("ix_pipeline_traces_stage"), table_name="pipeline_traces")
    op.drop_index(op.f("ix_pipeline_traces_created_at"), table_name="pipeline_traces")
    op.drop_index(op.f("ix_pipeline_traces_canonical_event_id"), table_name="pipeline_traces")
    op.drop_index(op.f("ix_pipeline_traces_article_id"), table_name="pipeline_traces")
    op.drop_index("idx_pipeline_traces_story_stage", table_name="pipeline_traces")
    op.drop_table("pipeline_traces")
    # ### end Alembic commands ###
