"""add domain extraction policy

Revision ID: 62039cc3c6f0
Revises: a5f3c2e1d9c8
Create Date: 2026-07-14 21:42:24.320386
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62039cc3c6f0"
down_revision: str | None = "a5f3c2e1d9c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_extraction_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("local_success_rate", sa.Float(), nullable=False),
        sa.Column("tavily_success_rate", sa.Float(), nullable=False),
        sa.Column("firecrawl_success_rate", sa.Float(), nullable=False),
        sa.Column("average_latency", sa.Float(), nullable=False),
        sa.Column("average_content_length", sa.Float(), nullable=False),
        sa.Column("last_success_provider", sa.String(length=50), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domain_extraction_policies_domain"),
        "domain_extraction_policies",
        ["domain"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_domain_extraction_policies_domain"), table_name="domain_extraction_policies"
    )
    op.drop_table("domain_extraction_policies")
    # ### end Alembic commands ###
