"""add_canonical_entities_and_story_kg

Revision ID: 693701833aef
Revises: b4e7a1c3d5f9
Create Date: 2026-06-20 09:29:46.820001
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '693701833aef'
down_revision: str | None = 'b4e7a1c3d5f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('wikidata_id', sa.String(length=50), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_entities_canonical_name'), 'canonical_entities', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_canonical_entities_wikidata_id'), 'canonical_entities', ['wikidata_id'], unique=False)
    op.create_index(op.f('ix_article_events_article_id'), 'article_events', ['article_id'], unique=False)
    op.add_column('stories', sa.Column('knowledge_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('story_entities', sa.Column('canonical_entity_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('story_entities_story_id_fkey'), 'story_entities', type_='foreignkey')
    op.create_foreign_key(None, 'story_entities', 'canonical_entities', ['canonical_entity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'story_entities', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_entities', type_='foreignkey')
    op.drop_constraint(None, 'story_entities', type_='foreignkey')
    op.create_foreign_key(op.f('story_entities_story_id_fkey'), 'story_entities', 'stories', ['story_id'], ['id'])
    op.drop_column('story_entities', 'canonical_entity_id')
    op.drop_column('stories', 'knowledge_graph')
    op.drop_index(op.f('ix_article_events_article_id'), table_name='article_events')
    op.drop_index(op.f('ix_canonical_entities_wikidata_id'), table_name='canonical_entities')
    op.drop_index(op.f('ix_canonical_entities_canonical_name'), table_name='canonical_entities')
    op.drop_table('canonical_entities')
    # ### end Alembic commands ###
