"""add_story_evolutions

Revision ID: 7578d7e9c7dc
Revises: 585a02b2a32c
Create Date: 2026-07-16 23:10:15.972998
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7578d7e9c7dc'
down_revision: Union[str, None] = '585a02b2a32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_evolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('parent_story_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('child_story_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_evolutions_article_id'), 'story_evolutions', ['article_id'], unique=False)
    op.create_index(op.f('ix_story_evolutions_created_at'), 'story_evolutions', ['created_at'], unique=False)
    op.create_index(op.f('ix_story_evolutions_event_type'), 'story_evolutions', ['event_type'], unique=False)
    op.create_index(op.f('ix_story_evolutions_run_id'), 'story_evolutions', ['run_id'], unique=False)
    op.create_index(op.f('ix_story_evolutions_story_id'), 'story_evolutions', ['story_id'], unique=False)
    op.drop_index(op.f('idx_ai_execution_records_article_id'), table_name='ai_execution_records')
    op.drop_index(op.f('idx_ai_execution_records_created_at'), table_name='ai_execution_records')
    op.drop_index(op.f('idx_ai_execution_records_stage'), table_name='ai_execution_records')
    op.drop_index(op.f('idx_ai_execution_records_story_id'), table_name='ai_execution_records')
    op.drop_index(op.f('idx_ai_execution_records_trace_id'), table_name='ai_execution_records')
    op.create_index(op.f('ix_ai_execution_records_article_id'), 'ai_execution_records', ['article_id'], unique=False)
    op.create_index(op.f('ix_ai_execution_records_created_at'), 'ai_execution_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_execution_records_stage'), 'ai_execution_records', ['stage'], unique=False)
    op.create_index(op.f('ix_ai_execution_records_story_id'), 'ai_execution_records', ['story_id'], unique=False)
    op.create_index(op.f('ix_ai_execution_records_trace_id'), 'ai_execution_records', ['trace_id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_story_candidate_id'), 'crawl_tasks', ['story_candidate_id'], unique=False)
    op.drop_index(op.f('idx_llm_traces_parent_llm_trace_id'), table_name='llm_traces')
    op.drop_index(op.f('idx_llm_traces_stage_run_id'), table_name='llm_traces')
    op.create_index(op.f('ix_llm_traces_parent_llm_trace_id'), 'llm_traces', ['parent_llm_trace_id'], unique=False)
    op.create_index(op.f('ix_llm_traces_stage_run_id'), 'llm_traces', ['stage_run_id'], unique=False)
    op.create_index(op.f('ix_story_candidates_collect_until'), 'story_candidates', ['collect_until'], unique=False)
    op.create_index(op.f('ix_story_candidates_created_at'), 'story_candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_story_candidates_priority'), 'story_candidates', ['priority'], unique=False)
    op.create_index(op.f('ix_story_candidates_status'), 'story_candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_candidates_status'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_priority'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_created_at'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_collect_until'), table_name='story_candidates')
    op.drop_index(op.f('ix_llm_traces_stage_run_id'), table_name='llm_traces')
    op.drop_index(op.f('ix_llm_traces_parent_llm_trace_id'), table_name='llm_traces')
    op.create_index(op.f('idx_llm_traces_stage_run_id'), 'llm_traces', ['stage_run_id'], unique=False)
    op.create_index(op.f('idx_llm_traces_parent_llm_trace_id'), 'llm_traces', ['parent_llm_trace_id'], unique=False)
    op.drop_index(op.f('ix_crawl_tasks_story_candidate_id'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_ai_execution_records_trace_id'), table_name='ai_execution_records')
    op.drop_index(op.f('ix_ai_execution_records_story_id'), table_name='ai_execution_records')
    op.drop_index(op.f('ix_ai_execution_records_stage'), table_name='ai_execution_records')
    op.drop_index(op.f('ix_ai_execution_records_created_at'), table_name='ai_execution_records')
    op.drop_index(op.f('ix_ai_execution_records_article_id'), table_name='ai_execution_records')
    op.create_index(op.f('idx_ai_execution_records_trace_id'), 'ai_execution_records', ['trace_id'], unique=False)
    op.create_index(op.f('idx_ai_execution_records_story_id'), 'ai_execution_records', ['story_id'], unique=False)
    op.create_index(op.f('idx_ai_execution_records_stage'), 'ai_execution_records', ['stage'], unique=False)
    op.create_index(op.f('idx_ai_execution_records_created_at'), 'ai_execution_records', ['created_at'], unique=False)
    op.create_index(op.f('idx_ai_execution_records_article_id'), 'ai_execution_records', ['article_id'], unique=False)
    op.drop_index(op.f('ix_story_evolutions_story_id'), table_name='story_evolutions')
    op.drop_index(op.f('ix_story_evolutions_run_id'), table_name='story_evolutions')
    op.drop_index(op.f('ix_story_evolutions_event_type'), table_name='story_evolutions')
    op.drop_index(op.f('ix_story_evolutions_created_at'), table_name='story_evolutions')
    op.drop_index(op.f('ix_story_evolutions_article_id'), table_name='story_evolutions')
    op.drop_table('story_evolutions')
    # ### end Alembic commands ###
