"""add_pipeline_failures_table

Revision ID: 89b3664b943f
Revises: c7e1f4a2b836
Create Date: 2026-06-23 13:05:01.638460
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '89b3664b943f'
down_revision: str | None = 'c7e1f4a2b836'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('caller', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('span_id', sa.UUID(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_runs_created_at'), 'function_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_function_runs_function_name'), 'function_runs', ['function_name'], unique=False)
    op.create_index(op.f('ix_function_runs_run_id'), 'function_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_function_runs_span_id'), 'function_runs', ['span_id'], unique=False)
    op.create_index(op.f('ix_function_runs_trace_id'), 'function_runs', ['trace_id'], unique=False)
    op.create_table('pipeline_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=False),
    sa.Column('error_category', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_failures_category', 'pipeline_failures', ['error_category'], unique=False)
    op.create_index('idx_pipeline_failures_resolved', 'pipeline_failures', ['resolved'], unique=False)
    op.create_index('idx_pipeline_failures_stage', 'pipeline_failures', ['stage'], unique=False)
    op.create_index(op.f('ix_pipeline_failures_article_id'), 'pipeline_failures', ['article_id'], unique=False)
    op.create_index(op.f('ix_pipeline_failures_run_id'), 'pipeline_failures', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_failures_story_id'), 'pipeline_failures', ['story_id'], unique=False)
    op.create_index(op.f('ix_pipeline_failures_timestamp'), 'pipeline_failures', ['timestamp'], unique=False)
    op.create_index(op.f('ix_pipeline_failures_trace_id'), 'pipeline_failures', ['trace_id'], unique=False)
    op.create_index(op.f('ix_article_entities_article_id'), 'article_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_events_event_fingerprint'), 'article_events', ['event_fingerprint'], unique=False)
    op.alter_column('cost_records', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cost_records', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cost_records', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('idx_cost_records_article_id'), table_name='cost_records')
    op.drop_index(op.f('idx_cost_records_story_id'), table_name='cost_records')
    op.create_index(op.f('ix_cost_records_article_id'), 'cost_records', ['article_id'], unique=False)
    op.create_index(op.f('ix_cost_records_created_at'), 'cost_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_records_story_id'), 'cost_records', ['story_id'], unique=False)
    op.alter_column('error_logs', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('idx_error_logs_created'), table_name='error_logs')
    op.drop_index(op.f('idx_error_logs_run_id'), table_name='error_logs')
    op.drop_index(op.f('idx_error_logs_story_id'), table_name='error_logs')
    op.drop_index(op.f('idx_error_logs_trace_id'), table_name='error_logs')
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_run_id'), 'error_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_error_logs_story_id'), 'error_logs', ['story_id'], unique=False)
    op.create_index(op.f('ix_error_logs_trace_id'), 'error_logs', ['trace_id'], unique=False)
    op.drop_index(op.f('idx_human_reviews_created'), table_name='human_reviews')
    op.create_index(op.f('ix_human_reviews_created_at'), 'human_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_human_reviews_story_id'), 'human_reviews', ['story_id'], unique=False)
    op.alter_column('llm_traces', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('llm_traces', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('llm_traces', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('llm_traces', 'latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('llm_traces', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('llm_traces', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('llm_traces', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('llm_traces', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_llm_traces_article_id'), table_name='llm_traces')
    op.drop_index(op.f('idx_llm_traces_created'), table_name='llm_traces')
    op.drop_index(op.f('idx_llm_traces_run_id'), table_name='llm_traces')
    op.drop_index(op.f('idx_llm_traces_story_id'), table_name='llm_traces')
    op.drop_index(op.f('idx_llm_traces_trace_id'), table_name='llm_traces')
    op.create_index(op.f('ix_llm_traces_article_id'), 'llm_traces', ['article_id'], unique=False)
    op.create_index(op.f('ix_llm_traces_created_at'), 'llm_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_traces_run_id'), 'llm_traces', ['run_id'], unique=False)
    op.create_index(op.f('ix_llm_traces_story_id'), 'llm_traces', ['story_id'], unique=False)
    op.create_index(op.f('ix_llm_traces_trace_id'), 'llm_traces', ['trace_id'], unique=False)
    op.alter_column('pipeline_runs', 'total_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('pipeline_runs', 'total_stages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pipeline_runs', 'successful_stages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pipeline_runs', 'failed_stages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_pipeline_runs_trace'), table_name='pipeline_runs')
    op.drop_constraint(op.f('pipeline_runs_trace_id_key'), 'pipeline_runs', type_='unique')
    op.create_index(op.f('ix_pipeline_runs_trace_id'), 'pipeline_runs', ['trace_id'], unique=True)
    op.drop_index(op.f('idx_prompt_versions_created'), table_name='prompt_versions')
    op.drop_index(op.f('idx_prompt_versions_hash'), table_name='prompt_versions')
    op.drop_constraint(op.f('prompt_versions_prompt_hash_key'), 'prompt_versions', type_='unique')
    op.create_index(op.f('ix_prompt_versions_created_at'), 'prompt_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_versions_prompt_hash'), 'prompt_versions', ['prompt_hash'], unique=True)
    op.alter_column('queue_metrics', 'active_jobs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('queue_metrics', 'waiting_jobs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('queue_metrics', 'completed_jobs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('queue_metrics', 'failed_jobs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('queue_metrics', 'dead_letter_jobs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('queue_metrics', 'avg_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('queue_metrics', 'worker_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_queue_metrics_captured'), table_name='queue_metrics')
    op.create_index(op.f('ix_queue_metrics_captured_at'), 'queue_metrics', ['captured_at'], unique=False)
    op.alter_column('retry_history', 'wait_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('idx_retry_history_created'), table_name='retry_history')
    op.drop_index(op.f('idx_retry_history_run_id'), table_name='retry_history')
    op.create_index(op.f('ix_retry_history_created_at'), 'retry_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_retry_history_run_id'), 'retry_history', ['run_id'], unique=False)
    op.alter_column('stage_runs', 'latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stage_runs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_stage_runs_article_id'), table_name='stage_runs')
    op.drop_index(op.f('idx_stage_runs_run_id'), table_name='stage_runs')
    op.drop_index(op.f('idx_stage_runs_story_id'), table_name='stage_runs')
    op.drop_index(op.f('idx_stage_runs_trace_id'), table_name='stage_runs')
    op.create_index(op.f('ix_stage_runs_article_id'), 'stage_runs', ['article_id'], unique=False)
    op.create_index(op.f('ix_stage_runs_run_id'), 'stage_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_stage_runs_story_id'), 'stage_runs', ['story_id'], unique=False)
    op.create_index(op.f('ix_stage_runs_trace_id'), 'stage_runs', ['trace_id'], unique=False)
    op.alter_column('token_usage', 'input_tokens',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('token_usage', 'output_tokens',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('token_usage', 'total_tokens',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('token_usage', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('token_usage', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token_usage', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token_usage', 'avg_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_token_usage_date'), 'token_usage', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_date'), table_name='token_usage')
    op.alter_column('token_usage', 'avg_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('token_usage', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('token_usage', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('token_usage', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('token_usage', 'total_tokens',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('token_usage', 'output_tokens',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('token_usage', 'input_tokens',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_stage_runs_trace_id'), table_name='stage_runs')
    op.drop_index(op.f('ix_stage_runs_story_id'), table_name='stage_runs')
    op.drop_index(op.f('ix_stage_runs_run_id'), table_name='stage_runs')
    op.drop_index(op.f('ix_stage_runs_article_id'), table_name='stage_runs')
    op.create_index(op.f('idx_stage_runs_trace_id'), 'stage_runs', ['trace_id'], unique=False)
    op.create_index(op.f('idx_stage_runs_story_id'), 'stage_runs', ['story_id'], unique=False)
    op.create_index(op.f('idx_stage_runs_run_id'), 'stage_runs', ['run_id'], unique=False)
    op.create_index(op.f('idx_stage_runs_article_id'), 'stage_runs', ['article_id'], unique=False)
    op.alter_column('stage_runs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stage_runs', 'latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_retry_history_run_id'), table_name='retry_history')
    op.drop_index(op.f('ix_retry_history_created_at'), table_name='retry_history')
    op.create_index(op.f('idx_retry_history_run_id'), 'retry_history', ['run_id'], unique=False)
    op.create_index(op.f('idx_retry_history_created'), 'retry_history', ['created_at'], unique=False)
    op.alter_column('retry_history', 'wait_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_queue_metrics_captured_at'), table_name='queue_metrics')
    op.create_index(op.f('idx_queue_metrics_captured'), 'queue_metrics', ['captured_at'], unique=False)
    op.alter_column('queue_metrics', 'worker_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('queue_metrics', 'avg_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('queue_metrics', 'dead_letter_jobs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('queue_metrics', 'failed_jobs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('queue_metrics', 'completed_jobs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('queue_metrics', 'waiting_jobs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('queue_metrics', 'active_jobs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_prompt_versions_prompt_hash'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_created_at'), table_name='prompt_versions')
    op.create_unique_constraint(op.f('prompt_versions_prompt_hash_key'), 'prompt_versions', ['prompt_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_prompt_versions_hash'), 'prompt_versions', ['prompt_hash'], unique=False)
    op.create_index(op.f('idx_prompt_versions_created'), 'prompt_versions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_pipeline_runs_trace_id'), table_name='pipeline_runs')
    op.create_unique_constraint(op.f('pipeline_runs_trace_id_key'), 'pipeline_runs', ['trace_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pipeline_runs_trace'), 'pipeline_runs', ['trace_id'], unique=False)
    op.alter_column('pipeline_runs', 'failed_stages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pipeline_runs', 'successful_stages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pipeline_runs', 'total_stages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pipeline_runs', 'total_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_llm_traces_trace_id'), table_name='llm_traces')
    op.drop_index(op.f('ix_llm_traces_story_id'), table_name='llm_traces')
    op.drop_index(op.f('ix_llm_traces_run_id'), table_name='llm_traces')
    op.drop_index(op.f('ix_llm_traces_created_at'), table_name='llm_traces')
    op.drop_index(op.f('ix_llm_traces_article_id'), table_name='llm_traces')
    op.create_index(op.f('idx_llm_traces_trace_id'), 'llm_traces', ['trace_id'], unique=False)
    op.create_index(op.f('idx_llm_traces_story_id'), 'llm_traces', ['story_id'], unique=False)
    op.create_index(op.f('idx_llm_traces_run_id'), 'llm_traces', ['run_id'], unique=False)
    op.create_index(op.f('idx_llm_traces_created'), 'llm_traces', ['created_at'], unique=False)
    op.create_index(op.f('idx_llm_traces_article_id'), 'llm_traces', ['article_id'], unique=False)
    op.alter_column('llm_traces', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_traces', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('llm_traces', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('llm_traces', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('llm_traces', 'latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('llm_traces', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_traces', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_traces', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_human_reviews_story_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_created_at'), table_name='human_reviews')
    op.create_index(op.f('idx_human_reviews_created'), 'human_reviews', ['created_at'], unique=False)
    op.drop_index(op.f('ix_error_logs_trace_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_story_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_run_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.create_index(op.f('idx_error_logs_trace_id'), 'error_logs', ['trace_id'], unique=False)
    op.create_index(op.f('idx_error_logs_story_id'), 'error_logs', ['story_id'], unique=False)
    op.create_index(op.f('idx_error_logs_run_id'), 'error_logs', ['run_id'], unique=False)
    op.create_index(op.f('idx_error_logs_created'), 'error_logs', ['created_at'], unique=False)
    op.alter_column('error_logs', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_cost_records_story_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_created_at'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_article_id'), table_name='cost_records')
    op.create_index(op.f('idx_cost_records_story_id'), 'cost_records', ['story_id'], unique=False)
    op.create_index(op.f('idx_cost_records_article_id'), 'cost_records', ['article_id'], unique=False)
    op.alter_column('cost_records', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cost_records', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cost_records', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_article_events_event_fingerprint'), table_name='article_events')
    op.drop_index(op.f('ix_article_entities_article_id'), table_name='article_entities')
    op.drop_index(op.f('ix_pipeline_failures_trace_id'), table_name='pipeline_failures')
    op.drop_index(op.f('ix_pipeline_failures_timestamp'), table_name='pipeline_failures')
    op.drop_index(op.f('ix_pipeline_failures_story_id'), table_name='pipeline_failures')
    op.drop_index(op.f('ix_pipeline_failures_run_id'), table_name='pipeline_failures')
    op.drop_index(op.f('ix_pipeline_failures_article_id'), table_name='pipeline_failures')
    op.drop_index('idx_pipeline_failures_stage', table_name='pipeline_failures')
    op.drop_index('idx_pipeline_failures_resolved', table_name='pipeline_failures')
    op.drop_index('idx_pipeline_failures_category', table_name='pipeline_failures')
    op.drop_table('pipeline_failures')
    op.drop_index(op.f('ix_function_runs_trace_id'), table_name='function_runs')
    op.drop_index(op.f('ix_function_runs_span_id'), table_name='function_runs')
    op.drop_index(op.f('ix_function_runs_run_id'), table_name='function_runs')
    op.drop_index(op.f('ix_function_runs_function_name'), table_name='function_runs')
    op.drop_index(op.f('ix_function_runs_created_at'), table_name='function_runs')
    op.drop_table('function_runs')
    # ### end Alembic commands ###
