"""add_discovery_queue

Revision ID: bedb1fd68ec8
Revises: c3d4e5f6g7h8
Create Date: 2026-07-10 18:55:02.975856
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bedb1fd68ec8"
down_revision: str | None = "c3d4e5f6g7h8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Reference variables to satisfy CodeQL static analysis checks
_alembic_refs = (revision, down_revision, branch_labels, depends_on)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_queue",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("cluster_group_id", sa.UUID(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_retry_reason", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id"),
    )
    op.create_index(
        op.f("ix_discovery_queue_expires_at"), "discovery_queue", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_discovery_queue_state"), "discovery_queue", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_discovery_queue_state"), table_name="discovery_queue")
    op.drop_index(op.f("ix_discovery_queue_expires_at"), table_name="discovery_queue")
    op.drop_table("discovery_queue")
    # ### end Alembic commands ###
